name: Run Basic Crypto Tracker

on:
  schedule:
    # Runs every hour; adjust this timing if you want
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas python-dotenv

    - name: Run basic.py
      env:
        BYBIT_API_KEY: ${{ secrets.BYBIT_API_KEY }}
        BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
      run: |
        python basic.py
